// Informative fields about a file or attributes to a file.
// These attributes include file path, file size, last updated, and permissions. This
// also includes 3 different hash codes that are generated by 3 of the hashing algorithms such as
// MD5, SHA-256, and SHA-512.
public class FileInfo {
    public String filePath;
    public long fileSize;
    public long lastUpdated;
    public String permissions;
    public String MD5;
    public String SHA256;
    public String SHA512;

    /**
     * To construct a FileInfo object and sets its fields: file path, file size, last updated, and permissions
     * with designated values.
     * @param filePath The path to the file.
     * @param fileSize The length or size of a file.
     * @param lastUpdated When the file was last modified.
     * @param permissions Type of permissions to a file, i.e. read, write, or execute.
     */
    public FileInfo(String filePath, long fileSize,long lastUpdated, String permissions){
        this.filePath = filePath;
        this.fileSize = fileSize;
        this.lastUpdated = lastUpdated;
        this.permissions = permissions;
    }
}
